admin_example_book_index:
    methods: [GET]
    path: book
    controller: ZnExample\ComposerPackage\Symfony4\Admin\Controllers\BookController::index

admin_example_book_create:
    path: book/create
    methods: [GET,POST]
    controller: ZnExample\ComposerPackage\Symfony4\Admin\Controllers\BookController::create

admin_example_book_view:
    methods: [GET]
    path: book/view/{id}
    controller: ZnExample\ComposerPackage\Symfony4\Admin\Controllers\BookController::view
    requirements:
        id: '\d+'

admin_example_book_update:
    methods: [GET,POST]
    path: book/update/{id}
    controller: ZnExample\ComposerPackage\Symfony4\Admin\Controllers\BookController::update
    requirements:
        id: '\d+'

admin_example_book_delete:
    methods: [POST]
    path: book/delete/{id}
    controller: ZnExample\ComposerPackage\Symfony4\Admin\Controllers\BookController::delete
    requirements:
        id: '\d+'
